NP-6624 - DateGroupingExpr and DateTimeGroupingExpr
kgrgreer/foam3 pull request #1495
Opened 2022-03-10 18:03 UTC by tala-abuadas

https://nanopay.atlassian.net/browse/NP-6624

2022-03-12 19:27 UTC, jlhughes commented on src/foam/mlang/expr/DateTimeGroupingExpr.js
> +      of: 'foam.mlang.expr.DateTypes',
@lchanmann 
Another duplication 
foam.mlang.expr.DateTypes and 
foam.time.TimeUnit 
What dependencies do we have on expr.DateTypes?

2022-03-14 02:33 UTC, tharmaman requested changes

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          if ( this.dateGroupingType == 'DAYS' ) {
This should be comparing to the enum and not the string value like `foam.time.TimeUnit.DAY`

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          if ( getDateGroupingType().getName().equals("DAYS") ) {
Same here compare the enum and not the string value

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          else if ( this.dateGroupingType == 'MONTHS' ) {
same as above

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          else if ( this.dateGroupingType == 'YEARS' ) {
same as above

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          else if ( getDateGroupingType().getName().equals("MONTHS") ) {
same as above

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateGroupingExpr.js
> +          else if ( getDateGroupingType().getName().equals("YEARS") ) {
same as above

2022-03-14 02:33 UTC, tharmaman commented on src/foam/mlang/expr/DateTimeGroupingExpr.js
> + * Copyright 2020 The FOAM Authors. All Rights Reserved.
2022

2022-03-22 18:58 UTC, tharmaman approved these changes

2022-03-23 13:33 UTC, jlhughes approved these changes

2022-03-25 17:39 UTC, merged