Update Login view
kgrgreer/foam3 pull request #2685
Opened 2023-04-05 19:56 UTC by AlexeyGreer

2023-04-05 20:09 UTC, sarthak-marwaha requested changes

2023-04-05 20:09 UTC, sarthak-marwaha commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        columns: 6,
Shouldnt these be 12, 6,6 so that we dont break existing views?

2023-04-05 20:09 UTC, sarthak-marwaha commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        class: 'foam.u2.layout.GridColumns',
Same here

2023-04-05 20:09 UTC, sarthak-marwaha commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        var left = this.GUnit.create({ columns: this.columnsConfigRight })
Why is this backwards?

2023-04-05 20:12 UTC, AlexeyGreer commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        columns: 6,
Isn't it supposed to be half tho? 6+6 = 12

2023-04-05 20:14 UTC, AlexeyGreer commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        var left = this.GUnit.create({ columns: this.columnsConfigRight })
Its actually correct, and everything around it is wrong.

2023-04-05 20:18 UTC, AlexeyGreer commented on src/foam/u2/borders/SplitScreenGridBorder.js
> +        columns: 6,
When your right your right

2023-04-05 20:29 UTC, sarthak-marwaha commented on src/foam/u2/view/LoginView.js
> +          }});
```suggestion
          columnsConfigRight: {
            class: 'foam.u2.layout.GridColumns',
            columns: 6,
            lgColumns: 4,
            xlColumns: 4
            }, 
          columnsConfigLeft: { 
            class: 'foam.u2.layout.GridColumns',
            columns: 6,
            lgColumns: 8,
            xlColumns: 8
          }});
```

2023-04-05 20:30 UTC, sarthak-marwaha approved these changes

2023-04-05 21:15 UTC, AlexeyGreer commented
Dont merge yet

2023-04-06 15:14 UTC, sarthak-marwaha approved these changes

2023-04-06 15:18 UTC, merged