group by view
kgrgreer/foam3 pull request #956
Opened 2021-09-29 20:22 UTC by tala-abuadas

2021-09-29 20:58 UTC, sarthak-marwaha requested changes

2021-09-29 20:58 UTC, sarthak-marwaha commented on src/foam/u2/table/UnstyledTableView.js
> +      }
Do we need these anymore?

2021-09-29 20:58 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +    'selectedCol',
Why do we need this prop? We modify `this.data.groupBy` directly

2021-09-29 20:58 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +                      image = self.theme.glyphs.folderFill.getDataUrl({ fill: self.theme.primary3});
```suggestion
                      image = self.theme.glyphs.folderFill.getDataUrl({ fill: self.theme.primary3 });
```
Same for the next one

2021-10-01 14:01 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +  requires: ['foam.u2.view.GroupByViewRow', 'foam.u2.UnstyledTableView','foam.u2.view.SubColumnSelectConfig'],
```suggestion
  requires: [
  'foam.u2.view.GroupByViewRow',
  'foam.u2.UnstyledTableView',
  'foam.u2.view.SubColumnSelectConfig'
  ],
```

2021-10-01 14:31 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +    function render() {
Remove this render

2021-10-01 18:48 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +        //views[draggableIndex].prop.isPropertySelected = ! views[draggableIndex].prop.isPropertySelected;
remove comments

2021-10-01 18:48 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +      //views[draggableIndex].prop.isPropertySelected = ! views[draggableIndex].prop.isPropertySelected;
same here

2021-10-01 18:48 UTC, sarthak-marwaha commented on src/foam/u2/view/GroupByView.js
> +      if ( this.selectCol ) {
indent

2021-10-05 16:06 UTC, sarthak-marwaha reviewed
LGTM

2021-10-06 21:47 UTC, sarthak-marwaha approved these changes

2021-10-20 18:03 UTC, sarthak-marwaha commented on src/foam/u2/view/EditColumnsView.js
> -    'columnConfigPropView'
No trailing commas

2021-10-20 18:03 UTC, sarthak-marwaha commented on src/foam/u2/view/ColumnConfigView.js
> +  'foam.u2.CheckBox',
indent

2021-10-20 18:03 UTC, sarthak-marwaha commented on src/foam/u2/view/ColumnConfigView.js
> +  padding: 8px;
indent

2021-10-20 18:03 UTC, sarthak-marwaha commented on src/foam/u2/view/ColumnConfigView.js
> +                         image = self.theme.glyphs.folderOutline.getDataUrl({ fill: self.theme.grey4 });
fill here should be `grey2` to match the checkbox outline

2021-10-20 18:05 UTC, sarthak-marwaha commented on src/foam/u2/table/UnstyledTableView.js
> +  ],
trailing commas

2021-10-20 18:13 UTC, sarthak-marwaha commented on src/foam/u2/table/UnstyledTableView.js
> +      value: 120
Do we need to do this now that we have only one button?

2021-10-20 18:13 UTC, sarthak-marwaha commented on src/foam/u2/table/TableView.js
> +    ^th-editColumns {
Same here

2021-10-20 18:14 UTC, sarthak-marwaha commented on src/foam/u2/view/ColumnConfigView.js
> +      documentation: 'parent\'s on this onSelectionChanged function'
update documentation

2021-10-20 18:15 UTC, tala-abuadas commented on src/foam/u2/table/UnstyledTableView.js
> +      value: 120
no

2021-10-21 13:49 UTC, sarthak-marwaha approved these changes

2021-10-21 14:39 UTC, kgrgreer commented on src/foam/u2/view/LazyScrollManager.js
> +    ['currGroup_', undefined],
What is this line needed for? undefined isn't a valid default value

2021-10-21 22:46 UTC, merged